version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: forum-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=forum_user
      - DB_PASSWORD=forum_password
      - DB_NAME=forum_db
      - SESSION_SECRET=change_this_to_a_secure_random_string
    volumes:
      - ./web/uploads:/app/uploads
    depends_on:
      - db
    networks:
      - forum-network

  db:
    image: mysql:8.0
    container_name: forum-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=forum_db
      - MYSQL_USER=forum_user
      - MYSQL_PASSWORD=forum_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./web/database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - forum-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local

networks:
  forum-network:
    driver: bridge