version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: forum_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: forum
      MYSQL_USER: forumuser
      MYSQL_PASSWORD: forumpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - forum-network

  app:
    build: .
    container_name: forum_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - forum-network

networks:
  forum-network:

volumes:
  mysql_data: